### PR TITLE
fix #78

### LINKED ISSUE #78: [E0464]: multiple matching crates after using cargo check
Running `cargo check` creates a `.rmeta` file with a different hash than the actual rlib built. This makes `cargo test` unable to compile tests which import the tested crate for integration testing.

This travis build fails because of the duplicate files https://travis-ci.org/hdhoang/testee/jobs/285433441#L481
It runs fine after removing the `rmeta` file https://travis-ci.org/hdhoang/testee/builds/285434745#L443

This is possibly related to rust-lang/cargo#3501. Until `check` and `build` use the same metadata, this issue would hinder `compiletest-rs` adoption.

I think we can workaround this by removing the relevant rmeta files when building tests.

### PR DESCRIPTION
**Pull request by hdhoang**
These paths come from the rustc build environment, so I suppose cleaning their `*.rmeta` files here is appropriate.

I'm ignoring errors here because:
- These are build artifacts
- E0464 would return later in the build

### CODE REVIEW

**Comment by laumann** [comment]
@hdhoang Thanks for the PR!

The change looks pretty straight-forward, but I'm wondering if this added functionality belongs in `link_deps()` though - I see that the paths we want to clean may be constructed by `link_deps()`. However, it is not required to use `link_deps()`, but you might still want to functionality to clean out `*.rmeta` files. Could it be implemented as a separate method on `Config`?

**Comment by hdhoang** [comment]
I have moved this functionality to a separate method, and add a note about it in the README

File: src/common.rs [hunk 1]
```diff
@@ -233,6 +234,37 @@ impl Config {
...
+    pub fn clean_rmeta(&self) {
+        let varname = if cfg!(windows) {
+            "PATH"
+        } else if cfg!(target_os = "macos") {
+            "DYLD_LIBRARY_PATH"
+        } else {
+            "LD_LIBRARY_PATH"
+        };
+
+        let lib_paths = env::var(varname).unwrap_or_else(|e| {
```
Comment (laumann) [inline src/common.rs]: Why inspect the `PATH` variable? Isn't it the paths that end up on `self.target_rustcflags` that should be inspected? 

```
let mut cfg = compiletest::Config::default();
cfg.target_rustcflags = Some(" -L target/debug");
cfg.clean_rmeta();
```
Maybe `clean_rmeta()` actually needs to inspect `cfg.build_base`?

File: src/common.rs [hunk 2]
```diff
@@ -233,6 +234,37 @@ impl Config {
...
+            panic!(
```
Comment (laumann) [inline src/common.rs]: Could this be one line? I *really* don't like how rustfmt splits this on five lines...

File: src/common.rs (hunk 1 above)
Comment (laumann) [reply src/common.rs]: Actually, just curious, would it work any differently if you used the `tmp` feature?

Comment (hdhoang) [reply src/common.rs]: `test-project` uses `tmp`, while the example hdhoang/testee in #78 doesn't, and they behave the same.

AIUI, from the test's perspective, the tested crate's rlib is a dependency, thus it will be placed in the workspace's `target/{debug,release}/deps`. `cargo check (--release)` also places its `rmeta` there, causing this conflict.

mgattozzi/github-rs#109 is an example where breaking compile-tests out into another workspace avoids this issue. [diesel does the same][diesel_compile_tests], but in that case there are genuine `rlib` conflict.

[diesel_compile_tests]: https://github.com/diesel-rs/diesel/blob/master/diesel_compile_tests/Cargo.toml#L6

I couldn't see that directory anywhere in `Config`'s members, so I resorted to crudely iterating over `dylib_env_var`. (sidenote: I will update this to use `dylib_env_var` after #80 merges)

File: src/common.rs (hunk 2 above)
Comment (hdhoang) [reply src/common.rs]: I will restore `link_deps`'s formatting.

File: src/common.rs (hunk 1 above)
Comment (hdhoang) [reply src/common.rs]: This `target/{profile}/deps` path is defined in [`cargo::ops::cargo_rustc::Layout`][1], used by `Context` and isn't exposed by that struct. I think the most we can do is constructing it from the build profile. Should I switch over to that, if possible?

[1]: https://github.com/rust-lang/cargo/blob/873a081019d8efb1906ae44c9afaffeec21f7db5/src/cargo/ops/cargo_rustc/layout.rs#L59

Comment (hdhoang) [reply src/common.rs]: Ah I see what you mean now. I will look for it in `target_rustcflags`.

Comment (laumann) [reply src/common.rs]: :+1:

File: src/common.rs (hunk 2 above)
Comment (laumann) [reply src/common.rs]: Ok, thanks :-)

**Comment by hdhoang** [comment]
I have reworked `clean_rmeta`. Please have a look.

**Comment by antoyo** [comment]
@laumann Could you please take a look at this PR?
Thank you.

**Comment by laumann** [comment]
@antoyo Yes, sorry, I completely forgot about it! Thanks for reminding me!

@hdhoang I'll have a look now, sorry for the delay!

File: src/common.rs [hunk 3]
```diff
@@ -233,6 +234,26 @@ impl Config {
         self.target_rustcflags = Some(flags);
     }
 
+    /// Remove rmeta files from target `deps` directory
```
Comment (laumann) [inline src/common.rs]: I'd like a little more documentation here, to explain why this is useful. IIRC this feature is useful when working with `cargo check` vs `cargo build` because the two methods don't share any information.

**Comment by laumann** [comment]
@hdhoang LGTM modulo a little more documentation of `clean_rmeta()`

**Comment by hdhoang** [comment]
I have worked the commit message into the doc comment. Please have a look.

**Comment by laumann** [comment]
Did you just push this or did I completely miss it? Either way it looks good

**Comment by hdhoang** [comment]
Sorry, I often force push PRs. GitHub doesn't push new notifications for that event so I follow up with a comment.

**Comment by laumann** [comment]
That's alright, I was just wondering if I overlooked something again. It looks good to me, I'm ready to merge if you don't have any further changes.

**Comment by hdhoang** [comment]
I feel this is good to go now.
