### PR TITLE
Fix error message in test, run tests on AppVeyor

### LINKED ISSUE #113: Have AppVeyor build run tests in test-project
The AppVeyor build only builds the library on nightly and stable, it doesn't run the tests in the test-project folder.

Add appropriate steps to the build script to do:
```
$ cd test-project
$ cargo test
```

### PR DESCRIPTION
**Pull request by fpoli**
This fixes tests on Travis and enable tests on AppVeyor.

However, tests on AppVeyor are failing: https://ci.appveyor.com/project/fpoli/compiletest-rs/build/1.0.1
It's probably some Window-related issue (path separators...). I suggest to open a new issue, as I can't debug this easily.

Closes #113

### CODE REVIEW

**Comment by laumann** [comment]
This should fix #113, I think.

**Comment by laumann** [comment]
No, I think I can fix that though. You're right, it's related to spaces in paths.

**Comment by laumann** [comment]
Ok, I think if you do:

```diff
--- a/test-project/tests/tests.rs
+++ b/test-project/tests/tests.rs
@@ -9,7 +9,7 @@ fn run_mode(mode: &'static str) {
 
     config.mode = cfg_mode;
     config.src_base = PathBuf::from(format!("tests/{}", mode));
-    config.link_deps();
+    config.target_rustcflags = Some("-L target/debug -L target/debug/deps".to_string());
     config.clean_rmeta();
 
     compiletest::run_tests(&config);
```

It should work. I know it's a hack, but I'd rather have these tests running at the moment, than trying to solve the bigger underlying problem in compiletest (namely #81).

File: test-project/tests/compile-fail/trait-bounds-cant-coerce.rs [hunk 1]
```diff
@@ -23,8 +23,8 @@ fn c(x: Box<Foo+Sync+Send>) {
 fn d(x: Box<Foo>) {
     a(x); //~  ERROR mismatched types
           //~| expected trait `Foo + std::marker::Send`, found trait `Foo`
-          //~| expected type `std::boxed::Box<Foo + std::marker::Send + 'static>`
-          //~| found type `std::boxed::Box<Foo + 'static>`
+          //~| expected type `std::boxed::Box<(dyn Foo + std::marker::Send + 'static)>`
+          //~| found type `std::boxed::Box<(dyn Foo + 'static)>`
```
Comment (laumann) [inline test-project/tests/compile-fail/trait-bounds-cant-coerce.rs]: This fix seems simple, but I don't really understand why this is the fix?

**Comment by laumann** [comment]
Nice, :crossed_fingers: that the tests work. Thank you so much for doing this!

Once this is merged I'll put out a new version.

File: test-project/tests/compile-fail/trait-bounds-cant-coerce.rs (hunk 1 above)
Comment (fpoli) [reply test-project/tests/compile-fail/trait-bounds-cant-coerce.rs]: It's just what the latest nighty rustc outputs... they probably changed the text of the message.

Comment (laumann) [reply test-project/tests/compile-fail/trait-bounds-cant-coerce.rs]: Oh, interesting... That means that even if you write `Box<Trait>` the error message is going to write `Box<dyn Trait>` (or is it `Box<(dyn Trait)>`?). I wonder if that's intentional.

Comment (fpoli) [reply test-project/tests/compile-fail/trait-bounds-cant-coerce.rs]: That looks strange, indeed... I assumed that here we are testing that compiletest matches errors correctly, not that rustc produces the correct message.

Comment (laumann) [reply test-project/tests/compile-fail/trait-bounds-cant-coerce.rs]: To be honest, I just copied some tests from rustc's test suite when developing the test project - it was just to verify that things worked as expected, and for use as a future benchmark.

I think it's a result of the "`dyn` everywhere" approach: https://github.com/rust-lang/rust/commit/4b1808578a99b1a452b65f0bf27de4c8775e9105. In particular: https://github.com/rust-lang/rust/blob/master/src/test/ui/mismatched_types/trait-bounds-cant-coerce.stderr.

File: src/runtest.rs [hunk 2]
```diff
@@ -211,8 +211,12 @@ impl<'test> TestCx<'test> {
 
     fn check_correct_failure_status(&self, proc_res: &ProcRes) {
         // The value the rust runtime returns on failure
-        const RUST_ERR: i32 = 1;
-        if proc_res.status.code() != Some(RUST_ERR) {
+        let rust_err: i32 = if cfg!(feature = "stable") {
```
Comment (laumann) [inline src/runtest.rs]: I was afraid of this. The whole "support stable Rust" is starting to become unmaintainable :-/ The `check_correct_failure_status()` function is somewhat different in rustc/compiletest so this fix isn't that back-portable.

I suppose it's fine for now, but I think a bigger sync-up with the current rustc/compiletest would be a good idea. I just worry that it would stable support.

Would it be better to skip the tests for the stable feature?

Comment (fpoli) [reply src/runtest.rs]: Yeah, I agree

Comment (laumann) [reply src/runtest.rs]: OK, thanks, I've also filed #121. Once this passes, we should be good to go. Thanks again!

**Comment by laumann** [comment]
[0.3.13](https://crates.io/crates/compiletest_rs/0.3.13) is out!
